basePath: /
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:3000
info:
  contact: {}
  description: This is a sample server celler server.
  license:
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger GoCoach-API
  version: "1.0"
paths: {}
swagger: "2.0"
